import { NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";

/**
 * POST /api/config/env
 * 
 * Saves environment variables to .env.local file.
 * This is used during onboarding to set up API keys.
 * 
 * Note: This only works in local development mode.
 * In production (Vercel), environment variables are set via dashboard.
 */
export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { ANTHROPIC_API_KEY, SUPABASE_URL, SUPABASE_ANON_KEY, OPENAI_API_KEY } = body;

    // Read existing .env.local if it exists to preserve existing keys
    const envPath = path.join(process.cwd(), ".env.local");
    let existingEnv: Record<string, string> = {};
    
    try {
      const existingContent = await fs.readFile(envPath, "utf-8");
      // Parse existing .env.local file
      for (const line of existingContent.split("\n")) {
        const trimmed = line.trim();
        // Skip comments and empty lines
        if (!trimmed || trimmed.startsWith("#")) continue;
        const match = trimmed.match(/^([A-Z_]+)=(.*)$/);
        if (match) {
          const [, key, value] = match;
          existingEnv[key] = value;
        }
      }
    } catch {
      // File doesn't exist yet, that's fine
    }

    // Merge new values with existing ones (new values override existing)
    const envVars: Record<string, string> = { ...existingEnv };
    
    if (ANTHROPIC_API_KEY) {
      envVars.ANTHROPIC_API_KEY = ANTHROPIC_API_KEY;
    }
    if (OPENAI_API_KEY) {
      envVars.OPENAI_API_KEY = OPENAI_API_KEY;
    }
    if (SUPABASE_URL) {
      envVars.SUPABASE_URL = SUPABASE_URL;
    }
    if (SUPABASE_ANON_KEY) {
      envVars.SUPABASE_ANON_KEY = SUPABASE_ANON_KEY;
    }

    // Validate that at least one key is being saved
    const keysToSave = Object.keys(body).filter(key => 
      ["ANTHROPIC_API_KEY", "OPENAI_API_KEY", "SUPABASE_URL", "SUPABASE_ANON_KEY"].includes(key) && body[key]
    );
    
    if (keysToSave.length === 0) {
      return NextResponse.json(
        { success: false, error: "No environment variables provided to save" },
        { status: 400 }
      );
    }

    // Build .env.local content
    const envLines: string[] = [
      "# Inspiration App - Environment Variables",
      "# Auto-generated by onboarding wizard",
      "",
    ];

    // LLM Provider section
    if (envVars.ANTHROPIC_API_KEY || envVars.OPENAI_API_KEY) {
      envLines.push("# LLM Provider");
      if (envVars.ANTHROPIC_API_KEY) {
        envLines.push(`ANTHROPIC_API_KEY=${envVars.ANTHROPIC_API_KEY}`);
      }
      if (envVars.OPENAI_API_KEY) {
        envLines.push(`OPENAI_API_KEY=${envVars.OPENAI_API_KEY}  # Required for embeddings only`);
      }
      envLines.push("");
    }

    // Vector Database section
    if (envVars.SUPABASE_URL && envVars.SUPABASE_ANON_KEY) {
      envLines.push("# Vector Database (Supabase)");
      envLines.push(`SUPABASE_URL=${envVars.SUPABASE_URL}`);
      envLines.push(`SUPABASE_ANON_KEY=${envVars.SUPABASE_ANON_KEY}`);
      envLines.push("");
    }

    const envContent = envLines.join("\n");

    // Check if we're in a writable environment
    try {
      await fs.writeFile(envPath, envContent, "utf-8");
    } catch (writeError) {
      // This might happen in read-only environments (Vercel production)
      console.error("Cannot write .env.local:", writeError);
      return NextResponse.json(
        {
          success: false,
          error: "Cannot write environment file. In production, set variables via Vercel dashboard.",
        },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      message: "Environment variables saved to .env.local",
      saved: keysToSave,
      note: "Restart the dev server for changes to take effect",
    });
  } catch (error) {
    console.error("Error saving environment variables:", error);
    return NextResponse.json(
      { success: false, error: "Failed to save environment variables" },
      { status: 500 }
    );
  }
}

/**
 * GET /api/config/env
 * 
 * Checks if required environment variables are configured.
 * Does NOT return the actual values (security).
 * 
 * Note: Supabase is optional for small chat histories.
 * Only ANTHROPIC_API_KEY is truly required.
 */
export async function GET() {
  const configured = {
    anthropic: !!process.env.ANTHROPIC_API_KEY,
    supabase: !!process.env.SUPABASE_URL && !!process.env.SUPABASE_ANON_KEY,
    openai: !!process.env.OPENAI_API_KEY,  // For embeddings only
  };

  // Only Anthropic is truly required. Supabase is optional for small histories.
  const allRequired = configured.anthropic;

  return NextResponse.json({
    success: true,
    configured,
    allRequired,
    hasVectorDb: configured.supabase,
    missingRequired: !allRequired
      ? ["ANTHROPIC_API_KEY"]
      : [],
  });
}
